### ISSUE TITLE
[Error] flowSaver connect to server password@XX.XX.XX.XX:6002 fail

### ISSUE THREAD

**Issue by 873314461** [shadowsocks/shadowsocks-manager#138]
我已经在单台机器上安装完成，使用也没有问题，但是，在扩展到多台机器时，webgui与另一台机器的manager链接不上，错误为：
```
[Error] flowSaver connect to server password@XX.XX.XX.XX:6002 fail.
```
我尝试关闭防火墙，依然不行，我自己用Python写了一个小的Demo，测试发现6002端口没有被屏蔽，可以正常通讯。

看错误提示，我发现时flowSaver模块的问题，我尝试关闭这个模块，然后会得到一下错误信息：
```
[ERROR] system - Unhandled Rejection at: Promise Promise {
  <rejected> { Error: select "id", "name", "host", "port", "password", "method" from "server" order by "name" asc - SQLITE_ERROR: no such table: server
    at Error (native) errno: 1, code: 'SQLITE_ERROR' } } reason: { Error: select "id", "name", "host", "port", "password", "method" from "server" order by "name" asc - SQLITE_ERROR: no such table: server
    at Error (native) errno: 1, code: 'SQLITE_ERROR' }
```
### 运行环境：
OS: CentOS7 x86_64
npm: 3.10.10
nodejs: v6.9.4
ssmgr: shadowsocks-manager 0.5.37
shadowsocks-libev: 3.0.4

### 具体配置信息如下：
```
#webgui.yml

type: m
empty: false

manager:
  address: XX.XX.XX.XX:6002  # IP 地址没有问题
  password: '123456'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.03
        flow: 500000000
      day:
        price: 0.5
        flow: 7000000000
      week:
        price: 3
        flow: 50000000000
      month:
        price: 10
        flow: 200000000000
      season:
        price: 30
        flow: 200000000000
      year:
        price: 120
        flow: 200000000000
  email:
    use: true
    username: 'XXXX@email.com'
    password: 'password'
    host: 'smtp.email.com'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://yourwebsite.com'
    gcmSenderId: '456102641793'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  alipay:
    use: true
    appid: 2015012108272442
    notifyUrl: ''
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
db: 'webgui.sqlite'
```
```
#default.yml
type: s
empty: false

shadowsocks:
  address: 127.0.0.1:4000
  #portRange: 50000-51000,55000,55002

manager:
  address: 0.0.0.0:6002
  password: '123456'

db: 'db.sqlite'
```
