### ISSUE TITLE
验证支付宝签名时获取[sign]字段失败

### ISSUE THREAD

**Issue by 873314461** [shadowsocks/shadowsocks-manager#139]
错误信息如下：
```
{ message: '验证支付宝签名时获取[sign]字段失败',
  info: 
   { alipay_trade_precreate_response: 
      { code: '40002',
        msg: 'Invalid Arguments',
        sub_code: 'isv.invalid-app-id',
        sub_msg: '无效的AppID参数' } } }
```

###配置信息：
```
alipay:
    use: true
    appid: 2015012108272442
    notifyUrl: ''
    merchantPrivateKey: '好大一串'
    alipayPublicKey: '好大一串'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

```
