### ISSUE TITLE
E-mail 插件可以设置发件人名称么？

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#144]
目前显示的邮箱账户名。

**Comment by gyteng** [comment]
不可以

Cokebar Chi <notifications@github.com>于2017年3月21日 周二23:41写道：

**Comment by gyteng** [comment]
现在可以设置了，在配置文件的 email 项添加一个 `name` 字段即可

**Comment by cokebar** [comment]
添加字段后不生效
```
  email:
    use: true
    username: 'noreply@xxx.xxx'
    password: 'xxxxxxx'
    host: 'smtp.xxx.com'
    name: 'inn'
```
发件人姓名仍然为noreply
