### ISSUE TITLE
Changeable port number for email plugin

### ISSUE THREAD

**Issue by wzxjohn** [shadowsocks/shadowsocks-manager#150]
In email plugin,
https://github.com/shadowsocks/shadowsocks-manager/blob/055d7294935be7987d26b8f2da938e783a92c86c/plugins/email/index.js#L13

the port number has been hard code in source. Maybe read from config is better.

**Comment by wzxjohn** [comment]
Also need email.from config key to config the sender's address.

**Comment by wzxjohn** [comment]
email 插件的端口应个是可修改的，同时应个增加发件人地址字段，因为不是所有的 smtp 服务器都用邮件地址作为登陆名的。

**Comment by gyteng** [comment]
等我了解一下SMTP的细节先，多谢你的建议

**Comment by gyteng** [comment]
已经修复了  
在配置文件的`email`项，增加了可选项（后面三个）：

```
email:
    use: true
    username: 'xxx@xxx.com'
    password: 'xxx'
    host: 'smtp.xxx.com'
    port: 465
    name: 'xxx'
    email: 'xxx@xxx.com'
```
