### ISSUE TITLE
使用 telegram，flow 总是返回 No Flows

### ISSUE THREAD

**Issue by alanoy** [shadowsocks/shadowsocks-manager#156]
### What version of shadowsocks-manager are you using?
从 0.5.3x 开始就是了，现在用 0.5.50 一样

### What operating system are you using?
centos 7

### What version of Node.js are you using?
v7.5.0

### What did you do?
```
ssserver -m xxx -k xxx --manager-address 127.0.0.1:port
ssmgr -s 127.0.0.1:port -m 127.0.0.1:port
ssmgr -c telegram.yml --debug
```

### What is your config in detail (with all sensitive info masked)?
```yml
type: m
empty: false

shadowsocks:
  address: 127.0.0.1:port

manager:
  address: 127.0.0.1:port
  password: 'xxx'

plugins:
  telegram:
    token: 'xx'
    use: true
  flowSaver:
    use: true

db: 'telegram.sqlite'
```
