### ISSUE TITLE
密码重置链接bug

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#172]
### What version of shadowsocks-manager are you using?
v0.5.68

### What operating system are you using?
Ubuntu 16.04 LTS

### What version of Node.js are you using?
Nodejs 6.10.1

### What did you do?
前端nginx反代ssmgr-webgui，执行密码重置

### What did you expect to see?
```
请访问下列地址重置您的密码：
https://mydomain.com/home/password/reset/xxxxxxxxx
```

### What did you see instead?
```
请访问下列地址重置您的密码：
http://127.0.0.1:5777/home/password/reset/xxxxxxxxx
```
直接显示IP:Port肯定是有问题的，域名没法显示了

### What is your config in detail (with all sensitive info masked)?
```
type: m
empty: false

manager:
  address: 127.0.0.1:5775
  password: 'xxx‘

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.1
        flow: 1
      day:
        price: 1000
        flow: 1
      week:
        price: 1000
        flow: 1
      month:
        price: 1000
        flow: 1
      season:
        price: 1000
        flow: 1
      year:
        price: 1000
        flow: 200000000000
  email:
    use: true
    username: 'xxx'
    password: 'xxx'
    host: 'xxx'
    name: 'xxx'
    email: 'xxx'
    port: 465
  webgui:
    use: true
    host: '127.0.0.1'
    port: '5777'
    site: 'https://mydomain.com'
    gcmSenderId: 'xxx'
    gcmAPIKey: 'xxx'
  alipay:
    use: true
    appid: xxx
    notifyUrl: ''
    merchantPrivateKey: 'xxx'
    alipayPublicKey: 'xxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'
```
