### ISSUE TITLE
Flow data missing on UI

### ISSUE THREAD

**Issue by siuond** [shadowsocks/shadowsocks-manager#179]
### What version of shadowsocks-manager are you using?
`shadowsocks-libev 3.0.5`

### What operating system are you using?
`Debian 8 x86_64 GNU/Linux`

### What version of Node.js are you using?
`nodejs v6.10.2`

### What did you do?
installed `shadowsocks-manager@0.5.70` via command
```sh
$ sudo npm install -g shadowsocks-manager
```

### What did you expect to see?

Please refer to below.

### What did you see instead?
![photo](https://raw.githubusercontent.com/siuond/siuond.github.io/master/%E6%93%B7%E5%8F%96.PNG)

### What is your config in detail (with all sensitive info masked)?
```yaml
type: m
empty: false

manager:
    address: 127.0.0.1:4001
    password: 'xxxx'

plugins:
    flowSaver:
        use: true
    user:
        use: true
    account:
        use: true
        pay:
            hour:
                price: 0.05
                flow: 500000000
            day:
                price: 1
                flow: 5000000000
            week:
                price: 6.5
                flow: 35000000000
            month:
                price: 26.5
                flow: 200000000000
            season:
                price: 67
                flow: 200000000000
            year:
                price: 243
                flow: 200000000000
    email:
        use: true
        username: 'xxxx'
        password: 'xxxx'
        host: 'smtp.xxxx.net'
        port: 2525
        name: 'xxxx'
        email: 'noreply@xxxx.com'
    webgui:
        use: true
        host: '127.0.0.1'
        port: '8080'
        site: 'http://ss.xxx.com'
        gcmSenderId: '456102641792'
        gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXY'
    alipay:
        use: true
        appid: 'xxxx'
        notifyUrl: ''
        merchantPrivateKey: 'xxx'
        alipayPublicKey: 'xxx'
        gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'

```
