### ISSUE TITLE
可以访问web界面，无法连接

### ISSUE THREAD

**Issue by ccc1924** [shadowsocks/shadowsocks-manager#224]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
shadowsocks-manager 0.6.31

### What operating system are you using?
debian 8 

### What version of Node.js are you using?
6.10.3

### What did you do?
用systemctl启动ssmgr ssmgr-webgui ss-manager，可以访问webgui，客户端无法连接上shadowsocks
```
#ssmgr

[Unit]
Description=shadowsocks-manager
After=network.target

[Service]
Type=simple
User=www-data
Group=www-data
LimitNOFILE=32768
WorkingDirectory=/var/www/.ssmgr/
ExecStart=/usr/local/bin/ssmgr -c /var/www/.ssmgr/default.yml

[Install]
WantedBy=multi-user.target
```
```
# ss-manager

[Unit]
Description=ss-manager
After=network.target

[Service]
Type=simple
EnvironmentFile=/etc/default/ss-manager
User=www-data
Group=www-data
LimitNOFILE=32768
WorkingDirectory=/var/www/.shadowsocks/
ExecStart=/usr/bin/ss-manager -m aes-256-gcm -u --manager-address 127.0.0.1:6001

[Install]
WantedBy=multi-user.target
```
```
#ssmgr-webgui

[Unit]
Description=ssmgr-webgui
After=network.target

[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=/var/www/.ssmgr/
ExecStart=/usr/local/bin/ssmgr -c /var/www/.ssmgr/webgui.yml

[Install]
WantedBy=multi-user.target
```
```
type: s
empty: false

shadowsocks:
  address: 127.0.0.1:6001
  #portRange: 50000-51000,55000,55002

manager:
  address: 0.0.0.0:6002
  password: 'arWQZGRgY15GjlSh'

db: 'db.sqlite'
```
```
type: m
empty: false

manager:
  address: 0.0.0.0:6002
  password: 'arWQZGRgY15GjlSh'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.03
        flow: 500000000
      day:
        price: 0.5
        flow: 7000000000
      week:
        price: 3
        flow: 50000000000
      month:
        price: 10
        flow: 200000000000
      season:
        price: 30
        flow: 200000000000
      year:
        price: 120
        flow: 200000000000
  email:
    use: true
    username: 'xxx'
    password: 'xxx'
    host: 'xxx'
  webgui:
    use: true
    host: '127.0.0.1'
    port: '6003'
    gcmSenderId: '456102641793'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  alipay:
    use: true
    appid: 2015012104922471
    notifyUrl: ''
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'
```
如何解决
