### ISSUE TITLE
用 docker 运行未成功

### ISSUE THREAD

**Issue by yangxuan8282** [shadowsocks/shadowsocks-manager#233]
按照 README 里的命令运行没成功

```
docker run --name ssmgr -idt -v "$PWD/.ssmgr:/root/.ssmgr" --net=host gyteng/ssmgr
```

访问 SERVER_IP:PORT 没有响应，用 curl 127.0.0.1:4001  也没有返回信息

配置文件

```
cat .ssmgr/default.yml 
type: s
empty: false
shadowsocks:
  address: 127.0.0.1:6001
manager:
  address: 0.0.0.0:4001
  password: 'foobar'
db: 'ss.sqlite'
```

日志显示服务已启动：

```
 docker logs ssmgr
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-06-19 17:55:38.270] [INFO] system - System start.
```

用 `netstat -lnp` 查看端口开放情况发现 `4001` 端口已经打开

```
sudo netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1077/sshd       
tcp        0      0 0.0.0.0:4001            0.0.0.0:*               LISTEN      17064/node      
tcp6       0      0 :::7500                 :::*                    LISTEN      31806/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      31828/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1077/sshd       
tcp6       0      0 :::7000                 :::*                    LISTEN      31817/docker-proxy
udp        0      0 0.0.0.0:68              0.0.0.0:*                           865/dhclient    
udp        0      0 0.0.0.0:48713           0.0.0.0:*                           17064/node      
```
