### ISSUE TITLE
多服务器节点流量上报不正常

### ISSUE THREAD

**Issue by zoakerc** [shadowsocks/shadowsocks-manager#235]
### What version of shadowsocks-manager are you using?
0.6.65

### What operating system are you using?
Linux sakura-jp 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Linux vultr-us 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### What version of Node.js are you using?
v6.11.0

### What did you do?
使用 [shadowsocks 4.0.4](https://github.com/shadowsocks/shadowsocks-windows) 全局代理，**服务器只选择日本节点**，下载 [ideaIU-2017.1.5.exe](https://download-cf.jetbrains.com/idea/ideaIU-2017.1.5.exe)(498MB)，登录管理员账号查看服务器流量，重现 2 次的截图如下，**流量被平均上报到了 2 个节点中**

![Imgur](http://i.imgur.com/foR1Lur.png)

### What is your config in detail (with all sensitive info masked)?
**sakura-jp**
```yml
type: s
db:
  host: common-mysql #host
  user: ssmgr
  password: ssmgr
  database: ssmgr
```
**vultr-us**
```yml
type: s
db:
  host: common-mysql #host
  user: ssmgr
  password: ssmgr
  database: ssmgr
```
**scale**

| id | name | scale | method |
| -- | ------ | ------ | -------- |
| 1  | 日本 - 东京 | 1 | aes-128-gcm |
| 2  | 美国 - 洛杉矶 | 1 | aes-128-gcm |
