### ISSUE TITLE
添加端口和密码

### ISSUE THREAD

**Issue by Labradors** [shadowsocks/shadowsocks-manager#259]
每次注册新用户，添加端口和密码的时候报错
```
[2017-08-04 15:28:50.913] [INFO] system - { command: 'add', port: 8081, password: '4248233106' }
[2017-08-04 15:28:50.913] [ERROR] system - error
```

**Comment by gyteng** [comment]
没有详细的配置信息无法帮你判断错误

**Comment by Labradors** [comment]
@gyteng 
- shadowsocks.json

```
{
    "server":"xxxxxxxx",
    "server_port":8388,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"xxxxxxxxx",
    "timeout":60,
    "method":"rc4-md5",
    "fast_open": true
}
```

- config.yml

```
type: s
empty: false

shadowsocks:
  address: 127.0.0.1:8388
  portRange: 50000-51000

manager:
  address: 0.0.0.0:6001
  password: '123456'
db:
  host: 'xxxx'
  user: 'xxxx'
  password: 'xxxx'
  database: 'shadowsocks'
```
配置就是这样，帮我瞧瞧？
