### ISSUE TITLE
webgui 无法启动

### ISSUE THREAD

**Issue by cyang812** [shadowsocks/shadowsocks-manager#297]
错误信息如下：
```
root@vultr:~/.ssmgr# ssmgr -c webgui.yml 
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-10-11 03:57:22.358] [INFO] system - System start.
[2017-10-11 03:57:24.738] [ERROR] system - { Error: connect ECONNREFUSED 127.0.0.1:6002
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6002 }
[2017-10-11 03:57:24.750] [ERROR] flowSaver - connect to server 123456@127.0.0.1:6002 fail.
```

配置信息如下：
```
type: m

manager:
  address: 127.0.0.1:6002
  password: '123456'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  email:
    use: true
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: '45.76.144.115'
    gcmSenderId: '312'
    gcmAPIKey: 'AAAA:XXXXXXX'

db: 'webgui.sqlite'

```
