### ISSUE TITLE
enable webgui and freeAccount plugin in the same time

### ISSUE THREAD

**Issue by ylfzq** [shadowsocks/shadowsocks-manager#331]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-manager are you using?

shadowsocks-manager 0.10.12 + libev

### What operating system are you using?

ubuntu 16.04 and centos 7

### What version of Node.js are you using?

nodejs 6

### What did you do?

enable webgui and freeAccount plugin in the same time

### What did you expect to see?

these 2 plugins works fine

### What did you see instead?

can't connect to ss-server or connection was reset frequently. It seems that freeAccount plugin will close all listening ports and reopen a new one, which leads to webgui managed ports closed also.

I checked the log, it seems to send a clear command to ss-manager server side?

### What is your config in detail (with all sensitive info masked)?

```yml
type: m

manager:
  address: x.x.x.x:xxx
  password: xxx

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  email:
    use: true
    type: 'smtp'
    username: 'xxx'
    password: 'xxx'
    host: 'xxx'
  webgui:
    use: true
    host: 'x.x.x.x'
    port: 'xxx'
  freeAccount:
    use: true
    port: 2990-3000
    flow: 500000
    time: 28800
    address: 'x.x.x.x'
    method: 'aes-256-cfb'
    listen: 'x.x.x.x:xxx'
db: '/etc/.ssmgr/webgui.sqlite'
```
