### ISSUE TITLE
启动异常报错

### ISSUE THREAD

**Issue by Daemon-guo** [shadowsocks/shadowsocks-manager#343]
安装之后，启动ss.yml和webgui.yml失败

shadowsocks-libv正常启动，启动命令
`screen -dmS ss-manager ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000`

失败报错
```
[2017-12-17 22:17:28.798] [INFO] system - System start.
[2017-12-17 22:17:28.941] [INFO] system - Config file path:  /root/.ssmgr/ss.yml
[2017-12-17 22:17:29.310] [ERROR] system - socket error:  { Error: listen EADDRNOTAVAIL 13.113.159.201:4001
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '13.113.159.201',
  port: 4001 }
```

ss.yml配置文件
```
type: s
empty: false
    
shadowsocks:
    address: 127.0.0.1:4000

manager:
    address: 13.113.159.201:4001
    password: 'passwd'
    
db:
    host: '127.0.0.1'
    user: 'ss_manager'
    password: 'passwd'
    database: 'ss_manager'
```

webgui.yml配置文件
```
type: m
empty: false

manager:
  address: 13.113.159.201:4001
  password: 'passwd'   # 密码填写和ss.yml中一样

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  email:
    use: true
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8980'
    site: 'http://13.113.159.201'
    gcmSenderId: '456102641793'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'

db:
  host: '127.0.0.1'
  user: 'ss_manager'
  password: 'passwd'
  database: 'ss_manager'
```
