### ISSUE TITLE
ssmgr type s 的 manager 端口必须暴露给外网吗？

### ISSUE THREAD

**Issue by yhvicey** [shadowsocks/shadowsocks-manager#352]
假设配置如下：
```yml
type: s
empty: false

shadowsocks:
  address: 127.0.0.1:50998

manager:
  address: 0.0.0.0:50999
  password: '<my-passwd>'

db: 'ss.sqlite'
```
目前所有的服务都在同一台机器上，这个 50999 端口必须开放吗？我试了一下，如果在 webgui 中将服务器地址修改为 127.0.0.1:50999，可以修改成功，但所有账号的服务器也跟着变成了127.0.0.1。若修改为外网地址，则 50999 端口必须开放，否则无法修改成功。
用户使用的话需要这个端口吗？若不需要，应该怎么写配置文件呢？希望达到的效果是，服务器连接还是使用 127.0.0.1:50999，但是用户得到的地址是`www.example.com:<user-port>`，就是类似 alias的设置
