### ISSUE TITLE
webgui mysql db will return 403 unauthorizaed

### ISSUE THREAD

**Issue by damonYuan** [shadowsocks/shadowsocks-manager#393]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?

0.14.27

### What operating system are you using?

Ubuntu, MacOS

### What version of Node.js are you using?

curl -sL https://deb.nodesource.com/setup_6.x | bash -

### What did you do?

If change the db to using mysql,

```
db:
  host: 'WEBGUI_DB_HOST'
  port: 3306
  user: 'WEBGUI_DB_USER'
  password: 'WEBGUI_DB_PASSWORD'
  database: 'WEBGUI_DB_NAME'
```
the [users page](http://54.64.180.222/admin/user) cannot be loaded. 

> GET http://xx.xx.xx.xx/api/admin/user?group=-1&page=1&pageSize=30&search=&sort=id_asc&type=normal 403 (Forbidden)

But if changed back to 

```
db: 'webgui.sqlite'
```
, no problems at all.

### What did you expect to see?

Loading the page normally.

### What did you see instead?

The HUD spinning forever and 403 error code returned.

### What is your config in detail (with all sensitive info masked)?

```type: m

manager:
  address: WEBGUI_MANAGER_ADDRESS
  password: 'WEBGUI_MANAGER_PASSWORD'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.05
        flow: 500000000
      day:
        price: 0.5
        flow: 7000000000
      week:
        price: 3
        flow: 50000000000
      month:
        price: 10
        flow: 200000000000
      season:
        price: 30
        flow: 200000000000
      year:
        price: 120
        flow: 200000000000
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    username: 'WEBGUI_EMAIL_USERNAME'
    password: 'WEBGUI_EMAIL_PASSWORD'
    host: 'WEBGUI_EMAIL_HOST'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '6003'
    site: 'WEBGUI_SITE_DOMAIN'
    # cdn: 'http://xxx.xxx.com'
    # icon: 'icon.png'
    # skin: 'default'
    # googleAnalytics: 'UA-xxxxxxxx-x'
    gcmSenderId: '456102641793'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  alipay:
    use: true
    appid: 2015012104922471
    notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  # alipay:
  #   use: true
  #   appid: 2015012104922471
  #   notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
  #   merchantPrivateKey: 'xxxxxxxxxxxx'
  #   alipayPublicKey: 'xxxxxxxxxxx'
  #   gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  # webgui_telegram:
  #   use: true
  #   token: '191374681:AAw6oaVPR4nnY7T4CtW78QX-Xy2Q5WD3wmZ'
  # paypal:
  #   use: true
  #   mode: 'live' # sandbox or live
  #   client_id: 'At9xcGd1t5L6OrICKNnp2g9'
  #   client_secret: 'EP40s6pQAZmqp_G_nrU9kKY4XaZph'

#db:
#  host: 'WEBGUI_DB_HOST'
#  port: 3306
#  user: 'WEBGUI_DB_USER'
#  password: 'WEBGUI_DB_PASSWORD'
#  database: 'WEBGUI_DB_NAME'

# problem: do not know why if using mysql db, 403 error will be returned
db: 'webgui.sqlite'
```

**Comment by gyteng** [comment]
your config file is the old version format, watch the [wiki page](https://github.com/shadowsocks/shadowsocks-manager/wiki/WebGUI) for more details.

**Comment by damonYuan** [comment]
@gyteng I cannot find the difference between my version and the wiki page version. And even if I changed the version according to the wiki page, the problem still existing there. Please reopen this issue.

**Comment by gyteng** [comment]
If the version of MySQL is greater than 5.7, you have to close 'only_full_group_by'

**Comment by damonYuan** [comment]
@gyteng  still failed with the same 403 error, here is the test docker compose file: 

```
version: '3.2'

services:

  db:
    image: damonyuan/ss-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MANAGER_DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOSTS: db,db
      PMA_VERBOSES: ssmgr,webgui
      PMA_PORTS: 3306,3306
    ports:
      - 6004:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  ss:
    image: mritd/shadowsocks
    ports:
      - 6443:6443
      - 6500:6500/udp
    environment:
      SS_MODULE: "ss-server"
      SS_CONFIG: "-s 0.0.0.0 -p 6443 -m aes-256-cfb -k 123456 --fast-open -d 8.8.8.8 -d 8.8.4.4 -u -v --manager-address 127.0.0.1:6001"
      KCP_MODULE: "kcpserver"
      KCP_CONFIG: "-t 127.0.0.1:6443 -l :6500 -mode fast2"
      KCP_FLAG: "false"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  ssmgr:
    image: damonyuan/ss-mgr:latest
    environment:
      SS_PROXY_ADDRESS: ${SS_PROXY_ADDRESS}
      MANAGER_PASSWORD: ${MANAGER_PASSWORD}
      MANAGER_DB_PASSWORD: ${MANAGER_DB_PASSWORD}
      MANAGER_DB_NAME: ${MANAGER_DB_NAME}
      MANAGER_DB_HOST: ${MANAGER_DB_HOST}
      MANAGER_DB_USER: ${MANAGER_DB_USER}
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  webgui:
    image: damonyuan/ss-webgui:latest
    environment:
      WEBGUI_EMAIL_USERNAME: ${WEBGUI_EMAIL_USERNAME}
      WEBGUI_EMAIL_PASSWORD: ${WEBGUI_EMAIL_PASSWORD}
      WEBGUI_EMAIL_HOST: ${WEBGUI_EMAIL_HOST}
      WEBGUI_MANAGER_PASSWORD: ${WEBGUI_MANAGER_PASSWORD}
      WEBGUI_DB_PASSWORD: ${WEBGUI_DB_PASSWORD}
      WEBGUI_DB_NAME: ${WEBGUI_DB_NAME}
      WEBGUI_DB_HOST: ${WEBGUI_DB_HOST}
      WEBGUI_DB_USER: ${WEBGUI_DB_USER}
      WEBGUI_SITE_DOMAIN: ${WEBGUI_SITE_DOMAIN}
      WEBGUI_MANAGER_ADDRESS: ${WEBGUI_MANAGER_ADDRESS}
    depends_on:
      - db
    ports:
      - 6003:6003
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  db:
    driver: local
```
env file:
```
SS_PROXY_ADDRESS=ss
MANAGER_PASSWORD=123456
MANAGER_DB_PASSWORD=abcdefg
MANAGER_DB_NAME=ssmgr
MANAGER_DB_HOST=db
MANAGER_DB_USER=root
WEBGUI_MANAGER_PASSWORD=123456
WEBGUI_EMAIL_USERNAME=xxx
WEBGUI_EMAIL_PASSWORD=xxx
WEBGUI_EMAIL_HOST=smtp.gmail.com
WEBGUI_DB_PASSWORD=abcdefg
WEBGUI_DB_NAME=webgui
WEBGUI_DB_HOST=db
WEBGUI_DB_USER=root
WEBGUI_SITE_DOMAIN=http://127.0.0.1
WEBGUI_MANAGER_ADDRESS=ssmgr:6002
```
and you can run the test with command: 
```
export $(cat .env) && docker stack deploy --compose-file ss-compose.yml ss
```
please help.
