### ISSUE TITLE
sqlMessage: 'Table \'webgui.account_plugin\' doesn\'t exist'

### ISSUE THREAD

**Issue by damonYuan** [shadowsocks/shadowsocks-manager#396]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?

0.14.27

### What operating system are you using?

Ubuntu, MacOS

### What version of Node.js are you using?

curl -sL https://deb.nodesource.com/setup_6.x | bash -

### What did you do?

Login webgui

### What did you expect to see?

see users list

### What did you see instead?

```
[2018-04-23 16:02:00.022] [ERROR] flowSaver - { Error: ER_NO_SUCH_TABLE: Table 'webgui.account_plugin' doesn't exist
    at Query.Sequence._packetToError (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
    --------------------
    at Protocol._enqueue (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:208:25)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:152:18
    at Promise._execute (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:146:12)
    at Client_MySQL.query (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/method.js:15:34)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/runner.js:65:21
    at tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:574:26)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: 'Table \'webgui.account_plugin\' doesn\'t exist',
  sqlState: '42S02',
  index: 0,
  sql: 'select * from `account_plugin`' }
```

### What is your config in detail (with all sensitive info masked)?

```
manager:
  address: WEBGUI_MANAGER_ADDRESS
  password: 'WEBGUI_MANAGER_PASSWORD'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    type: 'smtp'
    username: 'WEBGUI_EMAIL_USERNAME'
    password: 'WEBGUI_EMAIL_PASSWORD'
    host: 'WEBGUI_EMAIL_HOST'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '6003'
    site: 'WEBGUI_SITE_DOMAIN'
    # cdn: 'http://xxx.xxx.com'
    # icon: 'icon.png'
    # skin: 'default'
    # googleAnalytics: 'UA-xxxxxxxx-x'
    gcmSenderId: '456102641793'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  alipay:
    use: true
    appid: 2015012104922471
    notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  # alipay:
  #   use: true
  #   appid: 2015012104922471
  #   notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
  #   merchantPrivateKey: 'xxxxxxxxxxxx'
  #   alipayPublicKey: 'xxxxxxxxxxx'
  #   gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  # webgui_telegram:
  #   use: true
  #   token: '191374681:AAw6oaVPR4nnY7T4CtW78QX-Xy2Q5WD3wmZ'
  # paypal:
  #   use: true
  #   mode: 'live' # sandbox or live
  #   client_id: 'At9xcGd1t5L6OrICKNnp2g9'
  #   client_secret: 'EP40s6pQAZmqp_G_nrU9kKY4XaZph'

#db:
#  host: 'WEBGUI_DB_HOST'
#  port: 3306
#  user: 'WEBGUI_DB_USER'
#  password: 'WEBGUI_DB_PASSWORD'
#  database: 'WEBGUI_DB_NAME'

# problem: do not know why if using mysql db, 403 error will be returned
db: 'webgui.sqlite'
```
