### ISSUE TITLE
shadowsocks-go supports manage multiple users

### ISSUE THREAD

**Issue by houstar** [shadowsocks/shadowsocks-manager#436]
+ Issue with [shadowsocks-go manage multiple users](https://github.com/shadowsocks/shadowsocks-go/issues/417)

### What version of shadowsocks-manager are you using?
```
shadowsocks-manager 0.20.7
```
### What operating system are you using?
```
Ubuntu 18.04 LTS
```
### What version of Node.js are you using?
```
v8.11.3
```

### What did you do?
1. Use shadowsocks-go instead of libev or python shadowsocks to support manage multiple users
 
```
#go get github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
# shadowsocks-server --manager-address 127.0.0.1:6001 -d
# docker run --name ssmgr-s -idt -v ~/.ssmgr:/root/.ssmgr --net=host gyteng/ssmgr ssmgr -c /root/.ssmgr/default.yml
# docker run --name ssmgr-m -idt -v ~/.ssmgr:/root/.ssmgr --net=host gyteng/ssmgr ssmgr -c /root/.ssmgr/webgui.yml
```
### What did you expect to see?
traffic/flow statistic is correct.

### What did you see instead?
![traffic statistic](https://cloud.githubusercontent.com/assets/15172509/16226112/8836480c-37dc-11e6-8daf-e5877bdfb918.png)

#### default.yml
```
[root@aeon .ssmgr]# cat default.yml
type: s

shadowsocks:
  address: 127.0.0.1:6001
  #portRange: 50000-51000,55000,55002

manager:
  address: 0.0.0.0:6002
  password: '123456'

db: 'db.sqlite'
```
#### webgui.yml
```
type: m

manager:
  address: 127.0.0.1:6002
  password: '123456'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  email:
    use: true
    type: 'smtp'
    username: 'username'
    password: 'password'
    host: 'smtp.gmail.com'
    proxy: 'socks://hostname:port/'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8989'
    site: 'http://mysite.com'

db: 'webgui.sqlite'
