### ISSUE TITLE
Enforce strict password policies

### ISSUE THREAD

**Issue by chrisx8** [shadowsocks/shadowsocks-manager#441]
### What version of shadowsocks-manager are you using?
0.22.2 (from `npm`)

### What operating system are you using?
Ubuntu 18.04.1 LTS

### What version of Node.js are you using?
v8.11.3

### What did you do?
I registered an account.

### What did you expect to see?
Some password policies, such as:
  - 8 or more characters
  - dictionary check
  - must include upper/lower case letters and numbers

### What did you see instead?
  - I registered with a password as simple as `1`

### What is your config in detail (with all sensitive info masked)?

```yaml
type: m

manager:
  address: ***
  password: '***'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    username: '***'
    password: '***'
    host: '***'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8000'
    site: '***'
    icon: 'icon.png'
    googleAnalytics: '***'
db: 'web.sqlite'
```
