### ISSUE TITLE
从0.11升级到当前版本之后页面打不开

### ISSUE THREAD

**Issue by Seraphli** [shadowsocks/shadowsocks-manager#507]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.28.0

### What operating system are you using?
Ubuntu 14.04

### What version of Node.js are you using?
8.12.0

### What did you do?
从0.11.7更新到了0.28.0

### What did you expect to see?
主页面现在是空白状态,而不是之前的界面.但是服务器启动显示正常,没有异常输出

### What is your config in detail (with all sensitive info masked)?
```
root@ubuntu:~/.ssmgr# cat default.yml 
type: s
empty: false

shadowsocks:
  address: 127.0.0.1:6001
  #portRange: 50000-51000,55000,55002

manager:
  address: 0.0.0.0:6002
  password: '123456'

db: 'db.sqlite'

# db:
#   host: '1.1.1.1'
#   user: 'root'
#   password: 'abcdefg'
#   database: 'ssmgr'
root@ubuntu:~/.ssmgr# cat webgui.yml 
type: m
empty: false

manager:
  address: 0.0.0.0:6002
  password: '123456'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  email:
    use: true
    username: '*@*'
    password: '*'
    host: '*'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '*'
    site: 'http://*.*.*.*'
    # cdn: 'http://xxx.xxx.com'
    # googleAnalytics: 'UA-xxxxxxxx-x'
    # gcmSenderId: '456102641793'
    # gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  alipay:
    use: false
    appid: 2015012104922471
    notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  paypal:
    use: false
    mode: 'live' # sandbox or live
    client_id: 'At9xcGd1t5L6OrICKNnp2g9'
    client_secret: 'EP40s6pQAZmqp_G_nrU9kKY4XaZph'

db: 'webgui.sqlite'
root@ubuntu:~/.ssmgr# 
```
