### ISSUE TITLE
是否可以提供非邮箱验证的方式进行初始化用户

### ISSUE THREAD

**Issue by Ahaochan** [shadowsocks/shadowsocks-manager#513]
### What version of shadowsocks-manager are you using?
shadowsocks-manager 0.28.9

### What operating system are you using?
Ubuntu 18.04

### What version of Node.js are you using?
node -v
v8.10.0

### What did you do?
提供非邮箱验证的方式进行初始化用户

我将`email`设置成`false`, 注册时仍然要使用邮箱验证.
```yml
    email:
        use: false
        username: 'username'
        password: 'password'
        host: 'smtp.your-email.com'
```

`mailgun`似乎需要域名, 我没有域名资源, 能否**不进行验证**或**提供非邮箱验证的方式**进行初始化用户
