### ISSUE TITLE
Error after starting ssmgr -c webgui.yml

### ISSUE THREAD

**Issue by smallprogram** [shadowsocks/shadowsocks-manager#514]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.28.9
### What operating system are you using?
Ubantu 18

### What version of Node.js are you using?
Node8.x

### What did you do?
我的ss.yml
```
type: s

shadowsocks:
  address: 127.0.0.1:4000
manager:
  address: 0.0.0.0:4001
  password: '123456'
db: 'ss.sqlite'
```
我的webgui.yml
```
type: m

manager:
  address: [myserverIP]:4001
  password: '123456'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    type: 'smtp'
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://[MyServerIP]' 
db: 'webgui.sqlite'

```
我开启了三个SSH，分别运行了如下命令，并且没有关闭
`ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000`
没有问题

`ssmgr -c ss.yml`
```
[2018-12-12T00:14:04.846] [INFO] system - System start.
[2018-12-12T00:14:04.890] [INFO] system - ~/.ssmgr/default.yml not found, make file for it.
[2018-12-12T00:14:05.029] [INFO] system - Config file path:  /root/.ssmgr/ss.yml
```
没有问题

`ssmgr -c webgui.yml`
```
[2018-12-12T00:14:52.108] [INFO] system - System start.
[2018-12-12T00:14:52.269] [INFO] system - Config file path:  /root/.ssmgr/webgui.yml
**.returning() is not supported by sqlite3 and will not have any effect.**
```
提示.returning() is not supported by sqlite3 and will not have any effect.，无法正常开启管理网站。

请问这该如何解决。
