### ISSUE TITLE
出现redis错误

### ISSUE THREAD

**Issue by HelloGit100** [shadowsocks/shadowsocks-manager#558]
### What version of shadowsocks-manager are you using?
shadowsocks-manager 0.31.6

### What operating system are you using?
Centos 7

### What version of Node.js are you using?
node   v11.10.1

### What did you do?

redis的配置：
/etc/redis.conf文件：
#设置了密码
requirepass helloredis

重启redis之后，使用redis-cli命令测试，没有问题。

### What did you see instead?

执行`ssmgr -c ss.yml`，

新建ssh连接，执行`ssmgr -c webgui.yml`，出现以下内容：

```
[2019-03-03T13:00:16.001] [ERROR] system - Unhandled Rejection at: Promise {} reason: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/usr/local/node/lib/node_modules/shadowsocks-manager/node_modules/ioredis/built/redis/event_handler.js:95:37)
    at Object.onceWrapper (events.js:285:13)
    at Socket.emit (events.js:197:13)
    at TCP._handle.close (net.js:611:12)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND your.redis.host your.redis.host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND your.redis.host your.redis.host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND your.redis.host your.redis.host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND your.redis.host your.redis.host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND your.redis.host your.redis.host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND your.redis.host your.redis.host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND your.redis.host your.redis.host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)

```

### What is your config in detail (with all sensitive info masked)?

- ss.yml内容：
```
type: s
shadowsocks:
  address: 127.0.0.1:6001
manager:
  address: 0.0.0.0:6002
  password: '123456'
db: 'ss.sqlite'
```

- webgui.yml内容：
```
type: m

manager:
  address: 服务器ip:6001
  password: '123456'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  email:
    use: true
    type: 'smtp'
    username: '邮箱'
    password: '密码'
    host: '邮箱smtp服务器'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '100'
    site: '网址'
    # icon: 'icon.png'
    # skin: 'default'
    # googleAnalytics: 'UA-xxxxxxxx-x'
    # gcmSenderId: '476902381496'
    # gcmAPIKey: 'AAAAGzddLRc:XXXXXXXXXXXXXX'
db: 'webgui.sqlite'

# 从 0.30 开始需要配置 redis
redis:
  host: '127.0.0.1'
  port: 6379
  password: 'helloredis'
  db: 0
```

谢谢
