### ISSUE TITLE
流量统计结果不展示

### ISSUE THREAD

**Issue by Tdickson3** [shadowsocks/shadowsocks-manager#597]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.32.17

### What operating system are you using?
Debian9

### What version of Node.js are you using?
v10.16.0

### What did you do?
按照正常流程配置使用，不久前其中一个节点的流量使用情况，在线端口情况web端都没有显示，其他节点都正常。

### What did you expect to see?
想知道这种情况可能是什么原因造成的，或者该如何解决

### What did you see instead?
出现问题的就是图片中第一个服务器，没有任何流量使用情况展示。
![image](https://user-images.githubusercontent.com/44915990/59809918-719a5400-9335-11e9-9ee3-c99e7fb6e6b7.png)

### What is your config in detail (with all sensitive info masked)?

```type: s
shadowsocks:
  address: 127.0.0.1:2222
manager:
  address: 0.0.0.0:1212
  password: 'password'
db: 'ss.sqlite'
```
```
type: m
empty: false
manager:
  address: 0.0.0.0:1212
  password: 'password'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true  
  email:
    use: true
    type: 'mailgun'
    baseUrl: 'https://api.mailgun.net/v3/mail.com'
    apiKey: 'key-dhskdsjdhssjdsjdajadkaka9b1dbd'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8088'
    site: 'http://ssmgr.com'
    skin: 'fs_bing'
  webgui_telegram:
    use: true
    token: '5803823254:AdakjakjakahbajakkaatyXyivvTzXAAE'
  giftcard:
    use: true  
db: 'webgui.sqlite'
redis:
  host: '127.0.0.1'
  password: 'password'
  db: 0
```
