### ISSUE TITLE
can't change default group configuration for new account

### ISSUE THREAD

**Issue by drshiki** [shadowsocks/shadowsocks-manager#604]
### What version of shadowsocks-manager are you using?

0.32.43
### What operating system are you using?

CentOS Linux release 7.2.1511
### What version of Node.js are you using?

v8.16.0
### What did you do?

I change the default group for new account in `Setting`->`Account Configuration`
### What did you expect to see?

configuration changes
### What did you see instead?

configuration didn't change, and I tried other configurations in this page also didn't work, everything remains previous setting when I reenter this page, is there a `confirm` button to apply changes????
### What is your config in detail (with all sensitive info masked)?

```
type: m
manager:
  address: xxxx.com:2345
  password: 'pw123'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  email:
    use: true
    type: 'smtp'
    username: 'verification@dam.moe'
    password: 'pw123'
    host: 'smtp.yandex.com'
  webgui:
    skin: 'bing'
    use: true
    host: '0.0.0.0'
    port: '8040'
    site: 'https://xxxx.com'
    # icon: 'icon.png'
    # skin: 'default'
    # googleAnalytics: 'UA-xxxxxxxx-x'
    # gcmSenderId: '476902381496'
    # gcmAPIKey: 'AAAAGzddLRc:XXXXXXXXXXXXXX'
    # google_login_client_id: '724695589056-p78tu8738t4fjel56yhe34qq34gjufsi.apps.googleusercontent.com'
    # google_login_client_secret: 'TjUd36YnQ-YUI2uUtQa_43Tl'
    # facebook_login_client_id: '9825686749820123'
    # facebook_login_client_secret: 'a46c6bb6f8281c23d2b74b43008c9c46'
    # github_login_client_id: '7c45c34c1de3ef937d37'
    # github_login_client_secret: 'd2768efe5258cfb9ce4da11ed7ddc334bc65756b'
  alipay:
    use: true
    appid: 2019062xxxxxxxxxx
    notifyUrl: 'https://ss.xxxx.com'
    merchantPrivateKey: '/root/a/rsa_private_key.pem'
    alipayPublicKey: '/root/a/alipay_public_key.txt'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
db: 'webgui.sqlite'
redis:
  host: 'myredis'
  port: 6379
  password: 'pw123'
  db: 0
```

I moved the webmgr from a host to another host, copying whole .ssmgr directory, and docker log don't output any infomation about this, and follows
```
[xxx-xxx@VM_0_6_centos .ssmgr]$ date
Tue Aug 20 19:25:09 CST 2019
[xxx-xxx@VM_0_6_centos .ssmgr]$ pwd
/home/xxx-xxx/webmgr/.ssmgr
[xxx-xxx@VM_0_6_centos .ssmgr]$ grep -rn ERROR logs/webgui/
logs/webgui/flowSaver.log:436:[2019-08-20T15:43:10.187] [ERROR] flowSaver - [server: 1] save flow error
logs/webgui/system.log:607:[2019-08-20T02:55:16.691] [ERROR] system - timeout
logs/webgui/system.log:608:[2019-08-20T02:55:26.795] [ERROR] system - timeout
logs/webgui/system.log:609:[2019-08-20T02:55:36.901] [ERROR] system - timeout
logs/webgui/system.log:610:[2019-08-20T02:55:38.511] [ERROR] system - Error: write after end
logs/webgui/system.log:619:[2019-08-20T02:55:47.005] [ERROR] system - timeout
logs/webgui/system.log:620:[2019-08-20T02:55:57.109] [ERROR] system - timeout
logs/webgui/system.log:621:[2019-08-20T02:55:58.884] [ERROR] system - Error: write after end
logs/webgui/system.log:633:[2019-08-20T02:56:02.467] [ERROR] system - Error: write after end
logs/webgui/system.log:642:[2019-08-20T02:56:08.616] [ERROR] system - Error: write after end
logs/webgui/system.log:651:[2019-08-20T02:56:20.901] [ERROR] system - Error: write after end
logs/webgui/system.log:3292:[2019-08-20T15:43:10.186] [ERROR] system - timeout
logs/webgui/account.log:367:[2019-08-20T02:55:16.691] [ERROR] account - Error: connect to ssmgr[s] timeout [xxxx.com:2345]
logs/webgui/account.log:375:[2019-08-20T02:55:26.795] [ERROR] account - Error: connect to ssmgr[s] timeout [xxxx.com:2345]
logs/webgui/account.log:383:[2019-08-20T02:55:36.901] [ERROR] account - Error: connect to ssmgr[s] timeout [xxxx.com:2345]
logs/webgui/account.log:391:[2019-08-20T02:55:47.005] [ERROR] account - Error: connect to ssmgr[s] timeout [xxxx.com:2345]
logs/webgui/account.log:399:[2019-08-20T02:55:57.109] [ERROR] account - Error: connect to ssmgr[s] timeout [xxxx.com:2345]
```
