### ISSUE TITLE
About webgui's servers page

### ISSUE THREAD

**Issue by git4wht** [shadowsocks/shadowsocks-manager#607]
shadowsocks-manager 0.33.20
Ubuntu 18.04.2 LTS
nodejs v10.16.3

I want to use manager with webgui to show multinodes and ports state.
I have three nodes,Each node has four ssmgr-servers with type [s].

On the Servers page.I can find these servers is online. 
But can not get the statistics.

node-A : 3 servers [ssmgr-s] , webgui [ssmgr-m] , redias
node-B : 3 servers [ssmgr-s]
node-C : 3 servers [ssmgr-s]

config files:
------------------------ server-1
```
type: s
shadowsocks:
  address: 127.0.0.1:9001
manager:
  address: 0.0.0.0:9011
  password: '************'
db: 'db/ssmgr_1.sqlite'
```
------------------------ server-2
```
type: s
shadowsocks:
  address: 127.0.0.1:9002
manager:
  address: 0.0.0.0:9012
  password: '************'
db: 'db/ssmgr_2.sqlite'
```
------------------------ server-3
```
type: s
shadowsocks:
  address: 127.0.0.1:9003
manager:
  address: 0.0.0.0:9013
  password: '************'
db: 'db/ssmgr_3.sqlite'
```
------------------------ webgui
```
type: m

manager:
  address: 0.0.0.0:9011
  password: '************'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    username: 'xxxxxxxxxx'
    password: 'xxxxxxxxxx'
    host: 'xxxxxxx'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
db: 'db/webgui.sqlite'
redis:
  host: 'nodeA-IP'
  port: 6379
  password: '********'
  db: 0
```
------------------------ redis.conf
```
bind 0.0.0.0
requirepass ********
supervised systemd
```
