### ISSUE TITLE
#BUG receive.socket.close is not a function

### ISSUE THREAD

**Issue by cxy930123** [shadowsocks/shadowsocks-manager#78]
Hi! I'm using the plugin 'telegram', and meet an error.
config file:
```yaml
plugins:
  telegram:
    token: '12345678:********************'
    use: true
  flowSaver:
    use: true
```
Then on tty1 run ```ssmgr```
Then on tty2 run ```ssmgr -t m```
Here an error occur on tty1:
```
/usr/lib/node_modules/shadowsocks-manager/services/server.js:92
      receive.socket.close();
                     ^

TypeError: receive.socket.close is not a function
    at checkData (/usr/lib/node_modules/shadowsocks-manager/services/server.js:84:22)
    at receiveData (/usr/lib/node_modules/shadowsocks-manager/services/server.js:28:3)
    at Socket.socket.on.data (/usr/lib/node_modules/shadowsocks-manager/services/server.js:106:5)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```
Did I do something wrong?

**Comment by gyteng** [comment]
run `node -v` and check your Node.js version.

2016-11-16 10:32 GMT+08:00 cxy930123 <notifications@github.com>:

**Comment by cxy930123** [comment]
on centos7.1
```
>node -v
v6.9.1
```

**Comment by gyteng** [comment]
Something missing in your config file, your file must like this:

```
type: s
empty: false

shadowsocks:
  address: 127.0.0.1:6001

manager:
  address: 127.0.0.1:6002
  password: '123456'

plugins:
  telegram:
    use: true
    token: 'xxxxxx'
  flowSaver:
    use: true
db: 'db.sqlite'
```

**Comment by cxy930123** [comment]
Actually, the full config file is as follows:
```
>cat ~/.ssmgr/default.yml
type: s
empty: false

shadowsocks:
  address: 127.0.0.1:6001

manager:
  address: 127.0.0.1:6002
  password: 'cn.xxxxxxxxxx.xxxxxxxx'

plugins:
  telegram:
    use: true
    token: '264084847:XXXXXXXXXXXXXXXXXXXX-XX--XXXXX'
  cli:
    use: false
  flowSaver:
    use: true
  email:
    use: false
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'
  freeAccount:
    use: false
    host: 'yourhost'
    port: 80
    managerPassword: '01020304'
    shadowsocks:
      method: aes-256-cfb
      startPort: 55000
      endPort: 65000
      flow: 100
      time: 60
    limit:
      user:
        day: 0
        week: 0
        month: 0
      global:
        day: 0
        week: 0
        month: 0

db: 'db.sqlite'
```
