### ISSUE TITLE
How to use with mysql?

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#99]

**Comment by gyteng** [comment]
I am working on it.

**Comment by cokebar** [comment]
看到demo里说可选mysql 以为已经可以了呢

**Comment by gyteng** [comment]
@cokebar I just add mysql support, you have to modify the yml config file like this:

```
db:
  host: '127.0.0.1'
  user: 'abc'
  password: 'xxxxx'
  database: 'ooooo'
```
